version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: timesheet-devops-db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - devops-network

  backend:
    build: .
    container_name: timesheet-backend
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/timesheet-devops-db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      LOGGING_FILE_NAME: /var/log/timesheet-devops.log
    depends_on:
      - mysqldb
    networks:
      - devops-network

volumes:
  mysql-data:

networks:
  devops-network:
    driver: bridge
